# filament_mappings.py

# Mapping for filament materials
MATERIAL_MAPPING = {
    "01": "PLA",
    "02": "Silk PLA",
    "03": "ABS",
    "04": "PETG",
    "05": "Nylon",
    "06": "TPU",
    "07": "PC",
    "08": "ASA",
    "09": "HIPS",
    "10": "PVA",
    "11": "Wood PLA",
    "12": "Carbon Fiber PLA",
    "13": "Metal PLA",
    "14": "Polycarbonate+",
    "15": "Flexible PLA",
    "16": "Tough PLA",
    "17": "High Temp PLA",
    "18": "PP (Polypropylene)",
    "19": "PEEK",
    "20": "PET",
    "21": "ABS+",
    "22": "PLA+",
    "23": "Bamboo Fiber PLA",
    "24": "Fiberglass PLA",
    "25": "PA12 (Nylon)",
    "26": "Carbon Fiber PETG",
    "27": "Carbon Fiber Nylon",
    "28": "Carbon Fiber PC",
    "29": "Fiberglass Nylon",
    "30": "Fiberglass PETG",
    "31": "Fiberglass PLA",
    "32": "Tungsten Filament",
    "33": "Copper PLA",
    "34": "Brass PLA",
    "35": "Glow-in-the-Dark PLA",
    "36": "Transparent PLA",
    "37": "Chalkboard PLA",
    "38": "HIPS (High Impact Polystyrene)",
    "39": "Conductive PLA",
    "40": "Rubber-like TPU",
    "41": "Polypropylene (PP)",
    "42": "EVA (Ethylene-Vinyl Acetate)",
    "43": "Glass Fiber PLA",
    "44": "Carbon Fiber PET",
    "45": "Aluminum Filament",
    "46": "Silicone-like TPU",
}

# Mapping for filament colors
COLOR_MAPPING = {
    "001": "White",
    "002": "Black",
    "003": "Green",
    "004": "Red",
    "005": "Blue",
    "006": "Yellow",
    "007": "Orange",
    "008": "Purple",
    "009": "Pink",
    "010": "Gray",
    "011": "Brown",
    "012": "Clear",
    "013": "Silver",
    "014": "Gold",
    "015": "Bronze",
    "016": "Teal",
    "017": "Turquoise",
    "018": "Lime Green",
    "019": "Magenta",
    "020": "Aqua",
    "021": "Beige",
    "022": "Copper",
    "023": "Ivory",
    "024": "Charcoal",
    "025": "Peach",
    "026": "Lavender",
    "027": "Cyan",
    "028": "Violet",
    "029": "Emerald Green",
    "030": "Sky Blue",
    "031": "Mint Green",
    "032": "Electric Blue",
    "033": "Sunset Orange",
    "034": "Ruby Red",
    "035": "Deep Purple",
    "036": "Steel Blue",
    "037": "Cobalt Blue",
    "038": "Forest Green",
    "039": "Cherry Red",
    "040": "Butter Yellow",
    "041": "Pale Pink",
    "042": "Blush Pink",
    "043": "Salmon",
    "044": "Slate Gray",
    "045": "Sapphire Blue",
    "046": "Champagne",
    "047": "Onyx Black",
    "048": "Sunflower Yellow",
    "049": "Fuchsia",
    "050": "Lavender Blue",
    "051": "Burgundy",
    "052": "Olive Green",
    "053": "Tan",
    "054": "Frosted Clear",
    "055": "Royal Blue",
    "056": "Canary Yellow",
    "057": "Pistachio Green",
    "058": "Blush Red",
    "059": "Peacock Blue",
    "060": "Lemon Yellow",
    "061": "Dark Brown",
    "062": "Seafoam Green",
    "063": "Caribbean Blue",
    "064": "Chocolate Brown",
    "065": "Neon Green",
    "066": "Neon Pink",
    "067": "Neon Yellow",
    "068": "Neon Blue",
    "069": "Neon Orange",
    "070": "Metallic Silver",
    "071": "Metallic Gold",
    "072": "Metallic Copper",
    "073": "Metallic Bronze",
    "074": "Holographic",
    "075": "Fluorescent Pink",
    "076": "Fluorescent Green",
    "077": "Fluorescent Yellow",
    "078": "Fluorescent Blue",
    "079": "Fluorescent Orange",
    "080": "Glow in the Dark Green",
    "081": "Glow in the Dark Blue",
    "082": "Glow in the Dark Yellow",
    "083": "Glow in the Dark White",
    "084": "Glow in the Dark Pink",
    "085": "Glow in the Dark Red",
    "086": "Pearl White",
    "087": "Pearl Black",
    "088": "Pearl Blue",
    "089": "Pearl Green",
    "090": "Pearl Red",
    "091": "Pearl Pink",
    "092": "Pearl Yellow",
    "093": "Metallic Blue",
    "094": "Metallic Red",
    "095": "Metallic Green",
    "096": "Metallic Pink",
    "097": "Metallic Purple",
    "098": "Metallic Yellow",
    "099": "Matte White",
    "100": "Matte Black",
    "101": "Matte Red",
    "102": "Matte Blue",
    "103": "Matte Green",
    "104": "Matte Yellow",
    "105": "Matte Orange",
    "106": "Matte Purple",
    "107": "Matte Pink",
    "108": "Matte Gray",
    "109": "Matte Silver",
    "110": "Matte Gold",
    "111": "Metallic Silver Gloss",
    "112": "Metallic Gold Gloss",
    "113": "Neon Green Gloss",
    "114": "Neon Yellow Gloss",
    "115": "Neon Blue Gloss",
    "116": "Neon Orange Gloss",
    "117": "Neon Pink Gloss",
    "118": "Luminous Green",
    "119": "Luminous Blue",
    "120": "Luminous Yellow",
    "121": "Luminous Red",
    "122": "Luminous White",
    "123": "Holographic Blue",
    "124": "Holographic Pink",
    "125": "Holographic Green",
    "126": "Holographic Red",
    "127": "Holographic Silver",
    "128": "Holographic Gold",
    "129": "Soft Pink",
    "130": "Soft Blue",
    "131": "Soft Green",
    "132": "Soft Red",
    "133": "Soft Yellow",
    "134": "Soft Orange",
    "135": "Soft Purple",
    "136": "Soft Teal",
    "137": "Frosted Purple",
    "138": "Frosted Green",
    "139": "Frosted Blue",
    "140": "Frosted Pink",
    "141": "Frosted Yellow",
    "142": "Frosted Orange",
    "143": "Frosted Red",
    "144": "Frosted White",
    "145": "Dual Color Red & Blue",
    "146": "Dual Color Green & Yellow",
    "147": "Dual Color Black & White",
    "148": "Dual Color Purple & Pink",
    "149": "Dual Color Blue & Yellow",
    "150": "Dual Color Red & White",
    "151": "Dual Color Green & Black",
    "152": "Dual Color Teal & Orange",
    "153": "Dual Color Aqua & Purple",
    "154": "Dual Color Gold & Silver",
    "155": "Triple Color Red, Green, & Blue",
    "156": "Triple Color Yellow, Blue, & White",
    "157": "Triple Color Black, Red, & White",
    "158": "Triple Color Purple, Pink, & Blue",
    "159": "Triple Color Green, Yellow, & Orange",
    "160": "Triple Color Cyan, Black, & White",
    "161": "Triple Color Red, Black, & Yellow",
    "162": "Triple Color Blue, Green, & Gold",
    "163": "Triple Color Teal, Orange, & White",
    "164": "Triple Color Pink, White, & Gold",
}

# Mapping for filament brands
BRAND_MAPPING = {
    "01": "Bambu Lab",
    "02": "Overture",
    "03": "Polymaker",
    "04": "Prusa",
    "05": "Generic",
    "06": "Overture",
    "07": "MatterHackers",
    "08": "Ultimaker",
    "09": "eSun",
    "10": "Hatchbox",
    "11": "ColorFabb",
    "12": "Raise3D",
    "13": "Filamentum",
    "14": "3D Solutech",
    "15": "Sunlu",
    "16": "Proto-pasta",
    "17": "XYZprinting",
    "18": "Taulman3D",
    "19": "SainSmart",
    "20": "Priline",
    "21": "AmazonBasics",
    "22": "Gizmo Dorks",
    "23": "Innofil3D",
    "24": "PolyLite",
    "25": "Creality",
    "26": "FiloAlchemy",
    "27": "FormFutura",
    "28": "FilamentOne",
    "29": "M3D",
    "30": "CraftBot",
}